use_frameworks!
platform :ios, '9.0'

target 'KissToast_Example' do
  pod 'KissToast', :path => '../'

  target 'KissToast_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3"
        end
    end
end
